# docker-compose.yml

version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: ent-db
    restart: always
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ent-task
#      POSTGRES_INITDB_ARGS: --encoding=UTF8
#    volumes:
#      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      # Modified healthcheck test command
      test: [ "CMD-SHELL", "pg_isready -U username || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    networks:
      - app-network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: ent-task:latest  #from local image
    container_name: ent-task-api
    restart: always
    ports:
      - "8080:8080"
    environment:
      SERVER_ADDRESS: ":8080"
      DB_HOST: ent-db
      DB_PORT: "5432"
      DB_USER: "username"
      DB_PASSWORD: "password"
      DB_NAME: "ent-task"
      MIGRATIONS_ENABLED: true
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

#volumes:
#  postgres_data:
#    driver: local